language: java
jdk:
  - openjdk17

branches:
  only:
    - main

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r usearth-springboot3-webservice *
  - mkdir -p deploy
  - mv usearth-springboot3-webservice.zip deploy/usearth-springboot3-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: usearth-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY        # Travis CI 에서 IAM 사용자 엑세스 키
    secret_access_key: $AWS_SECRET_KEY    # Travis CI 에서 IAM 사용자 비밀 엑세스 키
    bucket: usearth-springboot-build         # S3 Bucket 이름
    key: usearth-springboot3-webservice.zip
    bundle_type: zip
    application: usearth-springboot3-webservice         # CodeDeploy 애플리케이션 이름
    deployment_group: usearth-springboot3-webservice-group   # CodeDeploy 배포 그룹 이름
    region: ap-northeast-2
    wait_until_deployed: true

notifications:
  email:
    recipients:
      - fruitsjh@gmail.com