language: java
jdk:
  - openjdk17

branches:
  only:
    - main

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp Dockerfile before-deploy/     # Dockerfile 복사하기
  - cp appspec.yml before-deploy/    # CodeDeploy 에게 필요한 appspec.yml 파일
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/usearth-springboot3-webservice.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: usearth-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY        # Travis CI 에서 IAM 사용자 엑세스 키
    secret_access_key: $AWS_SECRET_KEY    # Travis CI 에서 IAM 사용자 비밀 엑세스 키
    bucket: usearth-springboot-build         # S3 Bucket 이름
    key: usearth-springboot3-webservice.zip
    bundle_type: zip
    application: usearth-springboot3-webservice         # CodeDeploy 애플리케이션 이름
    deployment_group: usearth-springboot3-webservice-group   # CodeDeploy 배포 그룹 이름
    region: ap-northeast-2
    wait_until_deployed: true
    on:
      branch: main

notifications:
  email:
    recipients:
      - fruitsjh@gmail.com