language: java
jdk:
  - openjdk17

branches:
  only:
    - main

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r UsEarth_ISFive *
  - mkdir -p deploy
  - mv UsEarth_ISFive.zip deploy/UsEarth_ISFive.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: usearth-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main

notifications:
  email:
    recipients:
      - fruitsjh@gmail.com