spring:
  profiles:
    default: local
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(Pgsn4PZnORI2dcD9Avt7VyM6C+EbpSEGWRZkJcxCHphJ0ufTV4a2uUrs77Lt5Kx/zHBazUuVqXWD8T6lfGqJaim0xEG2RatgqK11tpWNsGuFcyImW1eksw==)
            client-secret: ENC(KQ6rMO/Da1Kgv7hqc8q2Gvyr4vZKsHo8wobjuzhjSkJRl3LcWMzzqY8yN6Se9S6Y)
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: email, profile

          naver:
            client-id: ENC(43xl/ULw5o9YYIBXpBB68zQGyEy2gDjn3A0pUxQZKRQ=)
            client-secret: ENC(u1b2Lknwe2uLCstE9LjDrLD+SszWjWOm)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name, email

          kakao:
            client-id: ENC(Dqdw3OSgV2mr2l0J8BTheK79WbfDj1ULY/n/Ij69ePkyY057IT7LafMkf0tV02q6)
            client-secret: ENC(AMBleYJRrAjMz4asoF3i5kozggzt8EsUkJ+Oa7sm5/Hl8+f1STzhzHWO3V1Q+u2j)
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost
      email-key: ${US_EARTH_JASYPT}
  mail:
    host: smtp.naver.com
    port: 465
    username: ${NAVER_ID}
    password: ${NAVER_PW}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

security:
  jwt:
    base-64-secret: ENC(TnrZl1n8V9qR+cc0a1qz5y4pRgBVpsOVyVRizPXH6YYV/iA44i0QhgyYgm5BXc+p7VAMs/+px7g6HZa+IZxryKvLCqS2LWkB/ERyALzdhGDkX29mjd2WvPvFvSNKbkbcRYVEjRD8u3JuItBSB2Gs62hqkIzrB63UrStpTu95rqiaG/CnwIf3G2PcR/0IgXcNZ6hnwGVxugf5qDwKrJx9dOYmp/XpTmJgVcQ0OF7aGs8=)
    refresh-secret: ENC(R8okHmeU81hCCRA/HBa+d8GjmRHhn1KXCzWRIqwdq/QOpe7s+G70DtyBDdg7eAN3Joe1IM2fLKlUDPQ1AX7qzk78fMgFYDQtdmJtF5zXH2SeGkhi36mkLDK/Wi1T18npmrsAEbHRlxLjrsX54qCQFPEiJQs+oF+sCa17iqJYhFCe5SFSYF/zbmpyByMP2mu5TaBkc3b/Ng8=)
    refresh-expiration-time: 600000
    access-expiration-time: 360000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${US_EARTH_JASYPT}
    property:
      prefix: ENC(
      suffix: )

file:
  upload-dir: ./static/

iamport:
  api:
    key: 6618814282336703
    secret: fFXxd28WQt23nUvIcSxkAZqsgbUg9NrTqg84kbFXtm139fxpRSYoUaiTVs0SueRS8s5mRlTDpUAZy5hu


---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(aYIbQMXpQB3T0GudGHm9PvfXKC+7gjXRiSrewgsKuFDiGKPwKDwV5sJl7HY0d/mNtA68YlpWXk43FvCtzYRffDmXJVjKDsj4)
    username: ENC(g36XRFVBRKteok6pSi3YJA==)
    password: ENC(OfSdWGXJcfg8Vcz6kkN8xA==)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(Pgsn4PZnORI2dcD9Avt7VyM6C+EbpSEGWRZkJcxCHphJ0ufTV4a2uUrs77Lt5Kx/zHBazUuVqXWD8T6lfGqJaim0xEG2RatgqK11tpWNsGuFcyImW1eksw==)
            client-secret: ENC(KQ6rMO/Da1Kgv7hqc8q2Gvyr4vZKsHo8wobjuzhjSkJRl3LcWMzzqY8yN6Se9S6Y)
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: email, profile

          naver:
            client-id: ENC(43xl/ULw5o9YYIBXpBB68zQGyEy2gDjn3A0pUxQZKRQ=)
            client-secret: ENC(u1b2Lknwe2uLCstE9LjDrLD+SszWjWOm)
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name, email

          kakao:
            client-id: ENC(Dqdw3OSgV2mr2l0J8BTheK79WbfDj1ULY/n/Ij69ePkyY057IT7LafMkf0tV02q6)
            client-secret: ENC(AMBleYJRrAjMz4asoF3i5kozggzt8EsUkJ+Oa7sm5/Hl8+f1STzhzHWO3V1Q+u2j)
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost
      email-key: ${US_EARTH_JASYPT}
  mail:
    host: smtp.naver.com
    port: 465
    username: ${NAVER_ID}
    password: ${NAVER_PW}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

security:
  jwt:
    base-64-secret: ENC(TnrZl1n8V9qR+cc0a1qz5y4pRgBVpsOVyVRizPXH6YYV/iA44i0QhgyYgm5BXc+p7VAMs/+px7g6HZa+IZxryKvLCqS2LWkB/ERyALzdhGDkX29mjd2WvPvFvSNKbkbcRYVEjRD8u3JuItBSB2Gs62hqkIzrB63UrStpTu95rqiaG/CnwIf3G2PcR/0IgXcNZ6hnwGVxugf5qDwKrJx9dOYmp/XpTmJgVcQ0OF7aGs8=)
    refresh-secret: ENC(R8okHmeU81hCCRA/HBa+d8GjmRHhn1KXCzWRIqwdq/QOpe7s+G70DtyBDdg7eAN3Joe1IM2fLKlUDPQ1AX7qzk78fMgFYDQtdmJtF5zXH2SeGkhi36mkLDK/Wi1T18npmrsAEbHRlxLjrsX54qCQFPEiJQs+oF+sCa17iqJYhFCe5SFSYF/zbmpyByMP2mu5TaBkc3b/Ng8=)
    refresh-expiration-time: 600000
    access-expiration-time: 3600000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${US_EARTH_JASYPT}
    property:
      prefix: ENC(
      suffix: )

file:
  upload-dir: ./static/

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        create_empty_composites:
          enabled: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: never
  data:
    redis:
      port: 6379
      host: localhost
      email-key: ${US_EARTH_JASYPT}
  mail:
    host: smtp.naver.com
    port: 465
    username: ${NAVER_ID}
    password: ${NAVER_PW}

jasypt:
  encryptor:
    password: ${US_EARTH_JASYPT}
